# Generated by Django 4.0.3 on 2023-06-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='status',
            field=models.ForeignKey(default='SUBMITTED', on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='presentations.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
