# Generated by Django 4.0.3 on 2023-06-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_alter_presentation_status_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='presentations.status'),
        ),
    ]
